<?php

/**
 * @file hooks and callback functions for origins_unique_title module.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function origins_unique_title_form_node_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $form['title']['widget'][0]['value']['#ajax'] = [
    'callback' => 'origins_unique_title_check_title',
    'disable-refocus' => TRUE,
    'event' => 'change',
    'wrapper' => 'title-unique',
    'progress' => [
      'type' => 'throbber',
      'message' => t('Checking if title is unique') . '...',
    ],
  ];

  $form['title_unique'] = [
    '#type' => 'html_tag',
    '#tag' => 'div',
    '#attributes' => [
      'id' => 'title-unique'
    ],
    '#weight' => $form['title']['#weight'] + 0.5,
  ];

  $form['#validate'][] = 'origins_unique_title_validate_title';
}

/**
 * AJAX callback for checking the node title.
 */
function origins_unique_title_check_title(array &$form, FormStateInterface $form_state) {
  $title = $form_state->getValue('title')[0]['value'];
  $excludes = [];

  if (\Drupal::routeMatch()->getRouteName() == 'node.add') {
    $bundle = \Drupal::routeMatch()->getParameter('node_type')->id();
  }
  else {
    $excludes[] = \Drupal::routeMatch()->getParameter('node')->id();
    $bundle = \Drupal::routeMatch()->getParameter('node')->bundle();
  }

  if (!empty($title) &&
    \Drupal::service('origins_unique_title.title_validator')->isTitleUnique($title, $bundle, $excludes) == FALSE) {


    $message = t("@type content with title '@title' already exists. You must choose a different title.", [
      '@title' => $title,
      '@type' => \Drupal::entityTypeManager()->getStorage('node_type')->load($bundle)->label(),
    ]);

    $render = $form['title_unique'];
    $render['#attributes']['class'] = 'form-item--error-message';
    $render['#value'] = '<strong>' . $message . '</strong>';
  }
  else {
    $render = $form['title_unique'];
  }

  return $render;
}

/**
 * Server side validation callback from the node form.
 */
function origins_unique_title_validate_title(array &$form, FormStateInterface $form_state) {
  $title = $form_state->getValue('title')[0]['value'];
  $excludes = [];

  if (\Drupal::routeMatch()->getRouteName() == 'node.add') {
    $bundle = \Drupal::routeMatch()->getParameter('node_type')->id();
  }
  else {
    $excludes[] = \Drupal::routeMatch()->getParameter('node')->id();
    $bundle = \Drupal::routeMatch()->getParameter('node')->bundle();
  }

  if (!empty($title) &&
    \Drupal::service('origins_unique_title.title_validator')->isTitleUnique($title, $bundle, $excludes) == FALSE) {

    $message = t("@type content with title '@title' already exists. You must choose a different title.", [
      '@title' => $title,
      '@type' => \Drupal::entityTypeManager()->getStorage('node_type')->load($bundle)->label(),
    ]);

    $form_state->setErrorByName('title', $message);
  }
}
