# Schema for the configuration files of the Origins: Workflow module.
origins_workflow.settings:
  type: config_object
  label: 'Origins: Workflow settings'
  mapping:
    example:
      type: string
      label: 'Example'
