<?php

/**
 * @file
 * Contains origins_qa.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Blocks all QA test accounts on production environments.
 *
 * @see config/optional/ultimate_cron.job.origins_qa_block_accounts.yml
 */
function origins_qa_block_qa_accounts() {
  if (getenv('PLATFORM_ENVIRONMENT_TYPE') !== 'production') {
    return;
  }

  $accounts = \Drupal::entityTypeManager()
    ->getStorage('user')
    ->loadByProperties(['roles' => 'qa']);

  foreach ($accounts as $account) {
    if ($account->isActive()) {
      try {
        $account->block();
        $account->save();
      }
      catch (\Throwable $error) {
        \Drupal::logger('origins_qa')->error('Error blocking QA account @name: @error', [
          '@name' => $account->getAccountName(),
          '@error' => $error->getMessage(),
        ]);
      }
    }
  }
}

/**
 * Implements hook_help().
 */
function origins_qa_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.origins_qa':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t("This module provides management operations for QA accounts. User accounts must be assigned the role 'qa' (Quality Assurance) to appear on the 'QA Accounts' section under 'People'.") . '</p>';
      $output .= '<h2>' . t('API') . '</h2>';
      $output .= '<p>' . t("The API provides commands to activate or deactivate QA accounts on non-production environments. The API requires that a token called 'ORIGINS_QA_API_TOKEN' is set within the Platform SH environment variables.") . '</p>';
      return $output;
  }
}
