<?php

/**
 * @file
 * Primary module hooks for origins_qa module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */

use Drupal\Core\Link;

/**
 * Implements hook_requirements().
 */
function origins_qa_requirements($phase) {
  $requirements = [];

  if ($phase == 'runtime') {
    $accounts = \Drupal::entityTypeManager()
      ->getListBuilder('user')
      ->getStorage()
      ->loadByProperties([
        'roles' => 'qa'
      ]);

    if(!empty($accounts)) {
      $active = 0;
      foreach ($accounts as $account) {
        ($account->isActive()) ? $active++ : NULL;
      }

      $summary = t('@active active of @total QA accounts.', [
        '@active' => $active,
        '@total' => count($accounts),
      ]);

      $description = [
        '#markup' => t('These should be removed or disabled on production sites. @link', [
          '@link' => Link::createFromRoute('QA account list', 'origins_qa.manager.list')->toString()])
      ];

      $requirements['origins_qa'] = [
        'title' => t('Origins QA accounts'),
        'severity' => REQUIREMENT_WARNING,
        'value' => $summary,
        'description' => $description,
      ];
    }
  }

  return $requirements;
}
