# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
version: 2.1

jobs:
  # Test that coding standards fit drupal.org definitions.
  coding_standards:
    docker:
      - image: circleci/php:8.0-apache-browsers
    steps:
      - checkout
      - run:
          name: Fetch phpcs and dependencies
          command: |
            composer require drupal/coder --prefer-stable --no-interaction --optimize-autoloader
            composer require slevomat/coding-standard --prefer-stable --no-interaction --optimize-autoloader
            # Move vendor directory up a level as we don't want to code-check all of that.
            mv vendor ../
      - run:
          name: Fetch phpcs convenience script
          command: |
            curl https://raw.githubusercontent.com/dof-dss/nidirect-drupal/development/phpcs.sh -o /home/circleci/project/phpcs.sh
            chmod +x /home/circleci/project/phpcs.sh
      - run:
          name: PHPCS analysis
          command: /home/circleci/project/phpcs.sh /home/circleci "/home/circleci/project"

  deprecated_code:
    docker:
      - image: circleci/php:8.0-apache-browsers
    environment:
      PROJECT_ROOT: "/home/circleci"
      steps:
        - attach_workspace:
            at: ./
        - run: sudo cp /home/circleci/origins_modules/.circleci/docker-php-circleci.ini /usr/local/etc/php/conf.d/
        - run:
            name: Deprecated code check
            command: |
              cd /home/circleci/project/web
              CHECK_DIRS="${PROJECT_ROOT}/origins_modules"
              ../vendor/bin/drupal-check $CHECK_DIRS

workflows:
  version: 2
  static_analysis:
    jobs:
      - coding_standards
      - deprecated_code
