<?php

/**
 * @file
 * Module install, uninstall and update functions.
 */

use Drupal\Core\Field\FieldPurger;
use Drupal\field\Entity\FieldStorageConfig;

/**
 * Implements hook_uninstall().
 */
function origins_common_uninstall() {
  if ($field_storage = FieldStorageConfig::loadByName('node', 'field_lb_search_enable')) {
    $field_storage->delete();
  }

  if ($field_storage = FieldStorageConfig::loadByName('node', 'field_lb_search_content')) {
    $field_storage->delete();
  }

  \Drupal::service(FieldPurger::class)->purgeBatch(10);
}

/**
 * Implementations of hook_update_N().
 */

/**
 * Remove redundant Layout Builder search fields.
 */
function origins_common_update_8001() {
  if ($field_storage = FieldStorageConfig::loadByName('node', 'field_lb_search_enable')) {
    $field_storage->delete();
  }

  if ($field_storage = FieldStorageConfig::loadByName('node', 'field_lb_search_content')) {
    $field_storage->delete();
  }
}
