field.formatter.settings.html_list_formatter:
  type: mapping
  mapping:
    list_type:
      type: string
      label: 'List type'
    list_classes:
      type: string
      label: 'List classes'
    display_item_link:
      type: boolean
      label: 'Display item link'
