<?php

declare(strict_types=1);

/**
 * @file
 * Provides a content issue entity type.
 */

use Drupal\Component\Serialization\Json;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Render\Element;
use Drupal\Core\Url;
use Drupal\node\Entity\NodeType;
use Drupal\node\NodeInterface;
use Drupal\user\UserInterface;

/**
 * Implements hook_preprocess_node().
 */
function origins_content_issue_preprocess_node(&$variables) {
  $route = \Drupal::routeMatch();

  if (!$route->getParameters()->has('node')) {
    return;
  }

  if (!\Drupal::currentUser()->hasPermission('create content issue')) {
    return;
  }

  /** @var NodeInterface $node */
  $node = $route->getParameters()->get('node');
  $node_type = NodeType::load($node->getType());
  $enabled = $node_type->getThirdPartySetting('origins_content_issue', 'content_issue_enabled');

  if ($enabled) {

    $variables['#attached']['library'][] =  'origins_content_issue/report-link';
    $variables['#attached']['drupalSettings']['origins_content_issue']['entity_id'] = $node->id();

    if ($route->getParameters()->has('node_revision')) {
      $node_revision = $route->getParameter('node_revision')->getLoadedRevisionId();
    } else {
      $node_revision = $node->getRevisionId();
    }

    $variables['#attached']['drupalSettings']['origins_content_issue']['revision_id'] = $node_revision;
  }

}

/**
 * Implements hook_theme().
 */
function origins_content_issue_theme(): array {
  return [
    'content_issue' => [
      'render element' => 'elements',
    ],
    'content_issue_row' => [
      'variables' => [
        'id' => '',
        'title' => '',
        'node_type' => '',
        'node_title' => '',
        'state' => '',
        'state_class' => '',
        'severity' => '',
        'severity_image' => '',
        'reporter' => '',
        'updated' => '',
        'module_path' => '',
      ],
    ],
    'content_issue_comment' => [
      'render element' => 'elements',
      'template' => 'content-issue-comment',
    ],
  ];
}


/**
 * Prepares variables for content issue templates.
 *
 * Default template: content-issue.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the content issue information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_content_issue(array &$variables): void {
  $variables['view_mode'] = $variables['elements']['#view_mode'];

  $issue = $variables['elements']["#content_issue"];

  $module_path = \Drupal::service('extension.path.resolver')->getPath('module', 'origins_content_issue');

  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }

  $content_nid = $variables['elements']["#content_issue"]->get('content_entity_id')->getString();
  $content_vid = $variables['elements']["#content_issue"]->get('content_entity_revision_id')->getString();

  if (empty($content_vid) || $content_nid === $content_vid) {
    $node_url = Url::fromRoute('entity.node.canonical', ['node' => $content_nid]);
  } else {
    $node_url = Url::fromRoute('entity.node.revision', ['node' => $content_nid, 'node_revision' => $content_vid]);
  }

  $comments = $issue->getComments();

  if ($comments) {
    $issue_comment_view_builder = \Drupal::entityTypeManager()->getViewBuilder('content_issue_comment');

    $rendered_comments = [];
    foreach ($comments as $comment) {
      $rendered_comments[] = $issue_comment_view_builder->view($comment, 'teaser');
    }

    $variables['comments'] = $rendered_comments;
  }

  $variables['content']['concerning'] = [
    '#type' => 'link',
    '#title' => t('View content (new window)'),
    '#url' => $node_url,
    '#attributes' => ['target' => '_blank'],
  ];

  if ($issue->access('update')) {
    $icon['image'] = [
      '#theme' => 'image',
      '#uri' => $module_path . '/assets/icon-edit.svg',
      '#alt' => t('Edit'),
      '#height' => 24,
      '#width' => 24,
    ];

    $icon['text'] = [
      '#markup' => t('Edit'),
    ];

    $variables['content']['edit_url'] = [
      '#type' => 'link',
      '#title' => \Drupal::service('renderer')->render($icon),
      '#url' => $issue->toUrl('edit-form'),
      '#attributes' => [
        'data-dialog-options' => Json::encode([
          'width' => 800,
        ]),
        'data-dialog-type' => 'modal',
        'class' => ['use-ajax', 'link-button', 'edit'],
      ],
    ];

    $variables['content']['comment']['add'] = [
      '#type' => 'link',
      '#title' => t('Add Comment'),
      '#url' => Url::fromRoute('origins_content_issue.comment.add', ['issue_id' => $issue->id()])
    ];
  }

  if ($issue->access('delete')) {
    $icon = [];
    $icon['image'] = [
      '#theme' => 'image',
      '#uri' => $module_path . '/assets/icon-delete.svg',
      '#alt' => t('Delete'),
      '#height' => 24,
      '#width' => 24,
    ];

    $icon['text'] = [
      '#markup' => t('Delete'),
    ];

    $variables['content']['delete_url'] = [
      '#type' => 'link',
      '#title' => \Drupal::service('renderer')->render($icon),
      '#url' => $issue->toUrl('delete-form'),
      '#attributes' => [
        'data-dialog-options' => Json::encode([
          'width' => 800,
        ]),
        'data-dialog-type' => 'modal',
        'class' => ['use-ajax', 'link-button', 'delete']
      ],
    ];
  }

  $variables['module_path'] = $module_path;
}

/**
 * Prepares variables for content issue comment templates.
 *
 * Default template: content-issue-comment.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the content issue comment information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_content_issue_comment(array &$variables): void {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  $variables['id'] = $variables["elements"]["#content_issue_comment"]->id();
  $variables['comment'] = $variables['elements']['comment'][0];
  $variables['author'] = $variables['elements']['uid'][0];
  $variables['date'] = $variables['elements']['created'][0];

  $variables['edit'] = [
    '#type' => 'link',
    '#title' => t('Edit'),
    '#url' => Url::fromRoute('origins_content_issue.comment.edit', ['comment_id' => $variables['id']]),
    '#attributes' => [
      'class' => ['use-ajax'],
    ],
  ];

  $variables['delete'] = [
    '#type' => 'link',
    '#title' => t('Delete'),
    '#url' => Url::fromRoute('origins_content_issue.comment.delete_confirm', ['comment_id' => $variables['id']]),
    '#attributes' => [
      'class' => ['use-ajax'],
      'data-dialog-type' => 'modal',
      'data-dialog-options' => Json::encode([
        'width' => 700,
        'minHeight' => 100,
        'title' => t('Are you sure you want to delete this comment?'),
      ]),
    ],
  ];
}

/**
 * Implements hook_user_cancel().
 */
function origins_content_issue_user_cancel($edit, UserInterface $account, $method): void {
  switch ($method) {
    case 'user_cancel_block_unpublish':
      // Unpublish content issues.
      $storage = \Drupal::entityTypeManager()->getStorage('content_issue');
      $content_issue_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->condition('status', 1)
        ->accessCheck(FALSE)
        ->execute();
      foreach ($storage->loadMultiple($content_issue_ids) as $content_issue) {
        $content_issue->set('status', FALSE)->save();
      }
      break;

    case 'user_cancel_reassign':
      // Anonymize content issues.
      $storage = \Drupal::entityTypeManager()->getStorage('content_issue');
      $content_issue_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->accessCheck(FALSE)
        ->execute();
      foreach ($storage->loadMultiple($content_issue_ids) as $content_issue) {
        $content_issue->setOwnerId(0)->save();
      }
      break;
  }
}

/**
 * Implements hook_ENTITY_TYPE_predelete() for user entities.
 */
function origins_content_issue_user_predelete(UserInterface $account): void {
  // Delete content issues that belong to this account.
  $storage = \Drupal::entityTypeManager()->getStorage('content_issue');
  $content_issue_ids = $storage->getQuery()
    ->condition('uid', $account->id())
    ->accessCheck(FALSE)
    ->execute();
  $storage->delete(
    $storage->loadMultiple($content_issue_ids)
  );
  // Delete old revisions.
  $content_issue_ids = $storage->getQuery()
    ->allRevisions()
    ->condition('uid', $account->id())
    ->accessCheck(FALSE)
    ->execute();
  foreach (array_keys($content_issue_ids) as $revision_id) {
    $storage->deleteRevision($revision_id);
  }
}

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function origins_content_issue_form_node_type_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  /** @var \Drupal\Core\Entity\EntityFormInterface $form_object */
  $form_object = $form_state->getFormObject();

  /** @var \Drupal\node\NodeInterface $node */
  $node = $form_object->getEntity();
  if (empty($node->id())) {
    return;
  }

  $node_type = NodeType::load($node->id());

  $form['origins_content_issue'] = [
    '#type' => 'details',
    '#title' => t('Content issue'),
    '#group' => 'additional_settings',
  ];

  $form['origins_content_issue']['content_issue_enabled'] = [
    '#type' => 'checkbox',
    '#title' => t('Enable content issue creation.'),
    '#description' => t('Allow users to notify the original content author of any issues they encounter.'),
    '#default_value' => $node_type->getThirdPartySetting('origins_content_issue', 'content_issue_enabled'),
  ];

  $form['#entity_builders'][] = 'origins_content_issue_form_node_type_form_builder';
}

/**
 * Entity builder for the origins_content_issue_form_node_type_form_alter().
 */
function origins_content_issue_form_node_type_form_builder($entity_type, $type, &$form, $form_state) {
  $type->setThirdPartySetting('origins_content_issue', 'content_issue_enabled', $form_state->getValue('content_issue_enabled'));
}

/**
 * Implements hook_moderation_sidebar_alter().
 */
function origins_content_issue_moderation_sidebar_alter(&$build, &$context) {
  if ($context instanceof NodeInterface) {

    if (\Drupal::currentUser()->hasPermission('view content issue') || in_array('administrator', \Drupal::currentUser()->getRoles())) {

      $node_type = NodeType::load($context->getType());
      if ($node_type->getThirdPartySetting('origins_content_issue', 'content_issue_enabled')) {

        $issue_manager = \Drupal::service('content_issue.manager');

        $issues = $issue_manager->getIssuesByContentID($context->id(), $context->getRevisionId());

        $build['actions']['secondary']['origins_content_issue'] = [
          '#title' => t('Content issues (@count)', ['@count' => count($issues)]),
          '#type' => 'link',
          '#url' => Url::fromRoute('entity.content_issue.collection', [
            'entity_id' => $context->id(),
            'revision_id' => $context->getRevisionId(),
          ]),
          '#attributes' => [
            'class' => [
              'moderation-sidebar-link',
              'button',
              'button--tertiary',
            ],
          ],
        ];
      }
    }
  }
}
