<?php

declare(strict_types=1);

/**
 * @file
 * Provides a content issue entity type.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Render\Element;
use Drupal\Core\Url;
use Drupal\node\Entity\NodeType;
use Drupal\node\NodeInterface;
use Drupal\user\UserInterface;

/**
 * Implements hook_preprocess_node().
 */
function origins_content_issue_preprocess_node(&$variables) {
  $route = \Drupal::routeMatch();

  if (!$route->getParameters()->has('node')) {
    return;
  }

  /** @var NodeInterface $node */
  $node = $route->getParameters()->get('node');
  $node_type = NodeType::load($node->getType());
  $enabled = $node_type->getThirdPartySetting('origins_content_issue', 'content_issue_enabled');

  if ($enabled) {
    $variables['#attached']['library'][] =  'origins_content_issue/report-link';
    $variables['#attached']['drupalSettings']['origins_content_issue']['entity_id'] = $node->id();

    if ($route->getParameters()->has('node_revision')) {
      $node_revision = $route->getParameter('node_revision')->getLoadedRevisionId();
    } else {
      $node_revision = $node->getRevisionId();
    }

    $variables['#attached']['drupalSettings']['origins_content_issue']['revision_id'] = $node_revision;
  }

}

/**
 * Implements hook_theme().
 */
function origins_content_issue_theme(): array {
  return [
    'content_issue' => [
      'render element' => 'elements',
    ],
    'content_issue_row' => [
      'variables' => [
        'id' => '',
        'title' => '',
        'node_type' => '',
        'node_title' => '',
        'state' => '',
        'state_class' => '',
        'severity' => '',
        'severity_image' => '',
        'reporter' => '',
        'updated' => '',
        'module_path' => '',
      ],
    ],
  ];
}

/**
 * Prepares variables for content issue templates.
 *
 * Default template: content-issue.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the content issue information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_content_issue(array &$variables): void {
  $variables['view_mode'] = $variables['elements']['#view_mode'];

  $module_path = \Drupal::service('extension.path.resolver')->getPath('module', 'origins_content_issue');

  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }

//  $variables['content']['add_comment'] = [
//    '#type' => 'link',
//    '#title' => t('Add Comment'),
//    '#url' => Url::fromRoute('comment.reply',
//      [
//        'entity_type' => 'content_issue',
//        'entity' => $variables["elements"]["#content_issue"]->id(),
//        'field_name' => 'comments'
//      ]),
//  ];

  $variables['content']['comments'] = $variables['content']["comments"][0]["comments"];
  $variables['module_path'] = $module_path;
}

/**
 * Implements hook_user_cancel().
 */
function origins_content_issue_user_cancel($edit, UserInterface $account, $method): void {
  switch ($method) {
    case 'user_cancel_block_unpublish':
      // Unpublish content issues.
      $storage = \Drupal::entityTypeManager()->getStorage('content_issue');
      $content_issue_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->condition('status', 1)
        ->accessCheck(FALSE)
        ->execute();
      foreach ($storage->loadMultiple($content_issue_ids) as $content_issue) {
        $content_issue->set('status', FALSE)->save();
      }
      break;

    case 'user_cancel_reassign':
      // Anonymize content issues.
      $storage = \Drupal::entityTypeManager()->getStorage('content_issue');
      $content_issue_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->accessCheck(FALSE)
        ->execute();
      foreach ($storage->loadMultiple($content_issue_ids) as $content_issue) {
        $content_issue->setOwnerId(0)->save();
      }
      break;
  }
}

/**
 * Implements hook_ENTITY_TYPE_predelete() for user entities.
 */
function origins_content_issue_user_predelete(UserInterface $account): void {
  // Delete content issues that belong to this account.
  $storage = \Drupal::entityTypeManager()->getStorage('content_issue');
  $content_issue_ids = $storage->getQuery()
    ->condition('uid', $account->id())
    ->accessCheck(FALSE)
    ->execute();
  $storage->delete(
    $storage->loadMultiple($content_issue_ids)
  );
  // Delete old revisions.
  $content_issue_ids = $storage->getQuery()
    ->allRevisions()
    ->condition('uid', $account->id())
    ->accessCheck(FALSE)
    ->execute();
  foreach (array_keys($content_issue_ids) as $revision_id) {
    $storage->deleteRevision($revision_id);
  }
}

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function origins_content_issue_form_node_type_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  /** @var \Drupal\Core\Entity\EntityFormInterface $form_object */
  $form_object = $form_state->getFormObject();

  /** @var \Drupal\node\NodeInterface $node */
  $node = $form_object->getEntity();
  if (empty($node->id())) {
    return;
  }

  $node_type = NodeType::load($node->id());

  $form['origins_content_issue'] = [
    '#type' => 'details',
    '#title' => t('Content issue'),
    '#group' => 'additional_settings',
  ];

  $form['origins_content_issue']['content_issue_enabled'] = [
    '#type' => 'checkbox',
    '#title' => t('Enable content issue creation.'),
    '#description' => t('Allow users to notify the original content author of any issues they encounter.'),
    '#default_value' => $node_type->getThirdPartySetting('origins_content_issue', 'content_issue_enabled'),
  ];

  $form['#entity_builders'][] = 'origins_content_issue_form_node_type_form_builder';
}

/**
 * Entity builder for the origins_content_issue_form_node_type_form_alter().
 */
function origins_content_issue_form_node_type_form_builder($entity_type, $type, &$form, $form_state) {
  $type->setThirdPartySetting('origins_content_issue', 'content_issue_enabled', $form_state->getValue('content_issue_enabled'));
}

/**
 * Implements hook_moderation_sidebar_alter().
 */
function origins_content_issue_moderation_sidebar_alter(&$build, &$context) {
  if ($context instanceof NodeInterface) {

    if (\Drupal::currentUser()->hasPermission('view content issue') || in_array('administrator', \Drupal::currentUser()->getRoles())) {

      $node_type = NodeType::load($context->getType());
      if ($node_type->getThirdPartySetting('origins_content_issue', 'content_issue_enabled')) {

        $issue_manager = \Drupal::service('content_issue.manager');

        $issues = $issue_manager->getIssuesByContentID($context->id(), $context->getRevisionId());

        $build['actions']['secondary']['origins_content_issue'] = [
          '#title' => t('Content issues (@count)', ['@count' => count($issues)]),
          '#type' => 'link',
          '#url' => Url::fromRoute('entity.content_issue.collection', [
            'entity_id' => $context->id(),
            'revision_id' => $context->getRevisionId(),
          ]),
          '#attributes' => [
            'class' => [
              'moderation-sidebar-link',
              'button',
              'button--tertiary',
            ],
          ],
        ];
      }
    }
  }
}

/**
 * Implements hook_0().
 */
function origins_content_issue_form_node_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  // Add only if the moderation sidebar exists
  if (isset($form['moderation_state'])) {
    // Ensure the secondary actions container exists.
    if (!isset($form['actions']['#secondary'])) {
      $form['actions']['#secondary'] = [];
    }

    // Add a custom link as a render array (e.g., button or link).
    $form['actions']['origins_content_issue'] = [
      '#type' => 'link',
      '#title' => t('Content issues'),
      '#url' => \Drupal\Core\Url::fromRoute('origins_content_issue.issue.add', ['entity_id' => $form_state->getFormObject()->getEntity()->id(), 'revision_id' => $form_state->getFormObject()->getEntity()->id()]),
      '#attributes' => [
        'class' => ['button', 'button--secondary'],
      ],
      '#weight' => 100,
      '#access' => TRUE, // You can conditionally allow this
      '#group' => 'secondary', // This ensures it's grouped with secondary actions.
    ];
  }
}


/**
 * Implements hook_preprocess_node().
 */
function origins_content_issue_preprocess_comment(&$variables) {

}

/**
 * Implements hook_theme_registry_alter().
 */
function origins_content_issue_theme_registry_alter(&$theme_registry) {
  if (isset($theme_registry['comment'])) {
    $theme_registry['comment']['path'] = \Drupal::service('extension.path.resolver')->getPath('module', 'origins_content_issue') . '/templates';
    $theme_registry['comment']['template'] = 'comment';
  }
}
