/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/
CKEDITOR.plugins.add('wsc', {
    init: function( editor ) {
        if ( editor.ui.addButton ) {
            editor.ui.addButton( 'Wsc', {
                label: 'default ckeditor button',
                id: 'Wsc',
                command: '',
                toolbar: 'Wsc,10',
            } );
        }
    }
} );
