<?php

/**
 * @file
 * Module file for Origins Forms.
 */

use Drupal\Core\Database\Database;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\node\NodeInterface;

/**
 * Implements hook_help().
 */
function origins_forms_help($route_name, RouteMatchInterface $route_match) {
  $output = '';
  switch ($route_name) {
    // Tour module help pages.
    case 'help.page.origins_forms':
      $output = '';
      $output .= '<h3>' . t("Form descriptions") . '</h3>';
      $output .= '<p>' . t("Moves the description on content, media and taxonomy form fields underneath the title.") . '</p>';
      $output .= '<h3>' . t("Field validation plugins") . '</h3>';
      $output .= '<h5>' . t("Unique list items") . '</h5>';
      $output .= '<p>' . t("Ensures uniqueness by enforcing a validation constraint that prevents duplicate entries in an item list-based field.") . '<br/>';
      $output .= t('To implement see: <a href="https://www.drupal.org/node/2015723#add_constraint_other_entity_base_field">https://www.drupal.org/node/2015723#add_constraint_other_entity_base_field</a>') . '</p>';
      break;

    default:
      break;
  }
  return $output;
}

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function origins_forms_form_taxonomy_term_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $config = \Drupal::config('origins_forms.settings');
  if ($config->get('enable_form_descriptions')) {
    $form['#attached']['library'][] = 'origins_forms/origins_forms.form_descriptions';
  }
}

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function origins_forms_form_node_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $config = \Drupal::config('origins_forms.settings');
  if ($config->get('enable_form_descriptions')) {
    $form['#attached']['library'][] = 'origins_forms/origins_forms.form_descriptions';
  }

  // Ensure we only process revisions warnings on node edit forms.
  if ($config->get('enable_revisions_warning') && str_contains($form_id, 'edit')) {
    /* @var $node \Drupal\node\NodeInterface */
    // @phpstan-ignore-next-line
    $node = $form_state->getFormObject()->getEntity();

    if (!$node instanceof NodeInterface) {
      return;
    }

    $count = Database::getConnection()
      ->select('node_revision', 'nr')
      ->condition('nr.nid', $node->id())
      ->countQuery()
      ->execute()
      ->fetchField();

    if ($count > $config->get('revisions_warning_caution_limit') && $count < $config->get('revisions_warning_lockdown_limit')) {
      \Drupal::messenger()->addWarning(t('This content has accumulated a high number of revisions. Consider removing older revisions to improve performance and reduce clutter. After @lockdown revisions you will be blocked from saving changes.', ['@lockdown' => $config->get('revisions_warning_lockdown_limit')]));
    }
    elseif ($count > $config->get('revisions_warning_lockdown_limit')) {
      if (in_array('administrator', \Drupal::currentUser()->getRoles())) {
        \Drupal::messenger()->addError(t('This content has exceeded the maximum number of revisions and will be locked from saving for non-administrator roles.'));
      }
      else {
        \Drupal::messenger()->addError(t('This content has accumulated a high number of revisions and is locked from saving. @revision-link to re-enable save functionality.', [
          '@revision-link' => $node->toLink('Remove older revisions', 'version-history')->toString()
        ]));

        $form['actions']['submit']['#disabled'] = TRUE;
        $form['actions']['preview']['#disabled'] = TRUE;
      }
    }
  }

}

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function origins_forms_form_media_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $config = \Drupal::config('origins_forms.settings');
  if ($config->get('enable_form_descriptions')) {
    $form['#attached']['library'][] = 'origins_forms/origins_forms.form_descriptions';
  }
}

/**
 * Implements hook_preprocess_fieldset().
 */
function origins_forms_preprocess_fieldset(&$variables) {

  // Add form descriptions class to field.
  $config = \Drupal::config('origins_forms.settings');
  if ($config->get('enable_form_descriptions')) {
    $variables['description_display'] = 'before';
    $desc = $variables['description_display'];

    if (!empty($variables['description']) && !empty($variables['description']['attributes'])) {
      $variables['description']['attributes']->addClass($desc);
    }
  }
}
