<?php

/**
 * @file
 * Module file for Origins Forms.
 */

use Drupal\Core\Database\Database;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\node\NodeInterface;

/**
 * Implements hook_help().
 */
function origins_forms_help($route_name, RouteMatchInterface $route_match) {
  $output = '';
  switch ($route_name) {
    case 'help.page.origins_forms':
      $output = '';
      $output .= '<h3>' . t("Form descriptions") . '</h3>';
      $output .= '<p>' . t("Moves the description on content, media and taxonomy form fields underneath the title.") . '</p>';

      $output .= '<h3>' . t("Field validation plugins") . '</h3>';
      $output .= '<h5>' . t("Unique list items") . '</h5>';
      $output .= '<p>' . t("Ensures uniqueness by enforcing a validation constraint that prevents duplicate entries in an item list-based field.") . '<br/>';
      $output .= t('To implement see: <a href="https://www.drupal.org/node/2015723#add_constraint_other_entity_base_field">https://www.drupal.org/node/2015723#add_constraint_other_entity_base_field</a>') . '</p>';
      break;
  }
  return $output;
}

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function origins_forms_form_taxonomy_term_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $config = \Drupal::config('origins_forms.settings');
  if ($config->get('enable_form_descriptions')) {
    $form['#attached']['library'][] = 'origins_forms/origins_forms.form_descriptions';
  }
}

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function origins_forms_form_node_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $config = \Drupal::config('origins_forms.settings');
  if ($config->get('enable_form_descriptions')) {
    $form['#attached']['library'][] = 'origins_forms/origins_forms.form_descriptions';
  }

  // Ensure we only process revisions warnings on node edit forms.
  if ($config->get('enable_revisions_warning') && str_contains($form_id, 'edit')) {
    /* @var $node \Drupal\node\NodeInterface */
    // @phpstan-ignore-next-line
    $node = $form_state->getFormObject()->getEntity();

    if (!$node instanceof NodeInterface) {
      return;
    }

    $caution_limit = $config->get('revisions_warning_caution_limit');
    $lockdown_limit = $config->get('revisions_warning_lockdown_limit');
    $revisions_excluded_ids = explode(' ', $config->get('revisions_warning_excluded'));

    $count = Database::getConnection()
      ->select('node_revision', 'nr')
      ->condition('nr.nid', $node->id())
      ->countQuery()
      ->execute()
      ->fetchField();

    if ($count > $caution_limit && $count <= $lockdown_limit) {
      \Drupal::messenger()->addWarning(t('This content has accumulated a high number of revisions (@revisions). Consider removing older revisions to improve performance and reduce clutter. After @lockdown_limit revisions you will be blocked from saving changes.', [
        '@revisions' => $count,
        '@lockdown_limit' => $lockdown_limit
      ]));
    }
    elseif ($count >= $lockdown_limit) {
      if (in_array($node->id(), $revisions_excluded_ids)) {
        \Drupal::messenger()->addWarning(t('This content has exceeded the maximum number of permissible revisions (@lockdown_limit). This content can be saved but we recommend deleting unnecessary @revision-link.', [
          '@lockdown_limit' => $lockdown_limit,
          '@revision-link' => $node->toLink('revisions', 'version-history')->toString()
        ]));
      }
      else {
        if (in_array('administrator', \Drupal::currentUser()->getRoles())) {
          \Drupal::messenger()->addError(t('This content has exceeded the maximum number of permissible revisions (@lockdown_limit) and will be locked from saving for non-administrator roles.', [
            '@lockdown_limit' => $lockdown_limit
          ]));
        }
        else {
          \Drupal::messenger()->addError(t('This content has exceeded the maximum number of permissible revisions (@lockdown_limit) is locked from saving. @revision-link to re-enable save functionality.', [
            '@lockdown_limit' => $lockdown_limit,
            '@revision-link' => $node->toLink('Remove older revisions', 'version-history')->toString()
          ]));

          $form['actions']['submit']['#disabled'] = TRUE;
          $form['actions']['preview']['#disabled'] = TRUE;
        }
      }
    }
  }

  if ($config->get('enable_unique_title')) {
    $form['title']['widget'][0]['value']['#ajax'] = [
      'callback' => 'origins_forms_check_unique_title',
      'event' => 'submit',
      'wrapper' => 'title-unique',
    ];

    $form['title_unique'] = [
      '#type' => 'html_tag',
      '#tag' => 'div',
      '#attributes' => [
        'id' => 'title-unique',
      ],
      '#weight' => $form['title']['#weight'] + 0,
    ];

    $form['#validate'][] = 'origins_forms_validate_unique_title';
  }

}

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function origins_forms_form_media_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $config = \Drupal::config('origins_forms.settings');
  if ($config->get('enable_form_descriptions')) {
    $form['#attached']['library'][] = 'origins_forms/origins_forms.form_descriptions';
  }
}

/**
 * Implements hook_preprocess_fieldset().
 */
function origins_forms_preprocess_fieldset(&$variables) {

  // Add form descriptions class to field.
  $config = \Drupal::config('origins_forms.settings');
  if ($config->get('enable_form_descriptions')) {
    $variables['description_display'] = 'before';
    $desc = $variables['description_display'];

    if (!empty($variables['description']) && !empty($variables['description']['attributes'])) {
      $variables['description']['attributes']->addClass($desc);
    }
  }
}

/**
 * AJAX callback for checking the node title.
 */
function origins_forms_check_unique_title(array &$form, FormStateInterface $form_state) {
  $title = $form_state->getValue('title')[0]['value'];
  $excludes = [];

  if (\Drupal::routeMatch()->getRouteName() == 'node.add') {
    $bundle = \Drupal::routeMatch()->getParameter('node_type')->id();
  }
  else {
    $excludes[] = \Drupal::routeMatch()->getParameter('node')->id();
    $bundle = \Drupal::routeMatch()->getParameter('node')->bundle();
  }

  $render = $form['title_unique'];

  if (!empty($title) && !\Drupal::service('origins_forms.title_validator')->isTitleUnique($title, $bundle, $excludes)) {
    $message = t("@type content with title '@title' already exists. You must choose a different title.", [
      '@title' => $title,
      '@type' => \Drupal::entityTypeManager()->getStorage('node_type')->load($bundle)->label(),
    ]);
    $render['#attributes']['class'] = 'form-item--error-message';
    $render['#value'] = '<strong>' . $message . '</strong>';
  }

  return $render;
}

/**
 * Server-side validation callback from the node form.
 */
function origins_forms_validate_unique_title(array &$form, FormStateInterface $form_state) {
  $title = $form_state->getValue('title')[0]['value'];
  $excludes = [];

  if (\Drupal::routeMatch()->getRouteName() == 'node.add') {
    $bundle = \Drupal::routeMatch()->getParameter('node_type')->id();
  }
  else {
    $excludes[] = \Drupal::routeMatch()->getParameter('node')->id();
    $bundle = \Drupal::routeMatch()->getParameter('node')->bundle();
  }

  if (!empty($title) && !\Drupal::service('origins_forms.title_validator')->isTitleUnique($title, $bundle, $excludes)) {
    $form_state->setErrorByName('title', t("@type content with title '@title' already exists. You must choose a different title.", [
      '@title' => $title,
      '@type' => \Drupal::entityTypeManager()->getStorage('node_type')->load($bundle)->label(),
    ]));
  }
}
