<?php

use Drupal\block\Entity\Block;
use Drupal\Core\Config\FileStorage;

/**
 * Implements hook_install().
 */
function origins_help_install() {
  // Disable the Claro help block which would otherwise
  // appear above our custom help section.
  $block = Block::load('claro_help');

  if ($block) {
    $block->setStatus(FALSE);
    $block->save();
  }
}

/**
 * Delete and import updated tours for existing installations.
 */
function origins_help_update_10001() {
  $module_path = \Drupal::service('extension.list.module')->getPath('origins_help');
  $source = new FileStorage($module_path . '/config/install');
  $config_factory = \Drupal::configFactory();

  foreach ($source->listAll() as $config_name) {
    $config_factory->getEditable($config_name)
      ->setData($source->read($config_name))
      ->save(TRUE);
  }

  $config_factory->getEditable('tour.tour.origins_moderation_sidebar')
    ->delete();
}

/**
 * Implements hook_uninstall().
 */
function origins_help_uninstall() {
  // Re-enable the Claro help block.
  $block = Block::load('claro_help');

  if ($block) {
    $block->setStatus(TRUE);
    $block->save();
  }
}
