<?php

/**
 * @file
 * Contains origins_form_descriptions.module.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter().
 */
function origins_form_descriptions_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $route_name = \Drupal::routeMatch()->getRouteName();

  // Add JS/CSS to entity add/edit and canonical forms.
  if (preg_match('/^entity.\w+.edit_form$/', $route_name)
    || preg_match('/^\w+.add$/', $route_name)
      || preg_match('/^entity.\w+.canonical$/', $route_name)) {

    $form['#attached']['library'][] = 'origins_form_descriptions/form_descriptions';
  }
}

/**
 * Implements hook_preprocess_form_element().
 */
function origins_form_descriptions_preprocess_form_element(&$variables) {
  if (empty($variables['description']['attributes'])) {
    return;
  }

  // Add a default hidden class to avoid visual jerkiness when loading.
  $variables['description']['attributes']->addClass('js-hide');
}
