<?php

/**
 * @file
 * Contains origins_form_descriptions.module.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function origins_form_descriptions_form_taxonomy_term_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $form['#attached']['library'][] = 'origins_form_descriptions/form_descriptions';
}

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function origins_form_descriptions_form_node_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $form['#attached']['library'][] = 'origins_form_descriptions/form_descriptions';
}

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function origins_form_descriptions_form_media_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $form['#attached']['library'][] = 'origins_form_descriptions/form_descriptions';
}

/**
 * Implements hook_preprocess_fieldset().
 */
function origins_form_descriptions_preprocess_fieldset(&$variables) {
  $variables['description_display'] = 'before';
  $desc = $variables['description_display'];
  if (!empty($variables['description']) && !empty($variables['description']['attributes'])) {
    $variables['description']['attributes']->addClass($desc);
  }
}

