<?php

/**
 * @file
 * Contains origins_form_descriptions.module.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function origins_form_descriptions_form_taxonomy_term_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $form['#attached']['library'][] = 'origins_form_descriptions/form_descriptions';
}

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function origins_form_descriptions_form_node_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $form['#attached']['library'][] = 'origins_form_descriptions/form_descriptions';
}

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function origins_form_descriptions_form_media_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $form['#attached']['library'][] = 'origins_form_descriptions/form_descriptions';
}

/**
 * Implements hook_theme_registry_alter
 */
function origins_form_descriptions_theme_registry_alter(&$theme_registry) {
  if (\Drupal::service('router.admin_context')->isAdminRoute()) {
    $theme_registry['fieldset__media_library_widget']['path'] = \Drupal::service('extension.list.module')->getPath('origins_form_descriptions') . '/templates/media-library';
  }
}
