<?php

declare(strict_types=1);

/**
 * @file
 * Provides a report entity type.
 */

use Drupal\Core\Render\Element;
use Drupal\user\UserInterface;

/**
 * Implements hook_theme().
 */
function origins_reporter_theme(): array {
  return [
    'origins_reporter_report' => ['render element' => 'elements'],
  ];
}

/**
 * Prepares variables for report templates.
 *
 * Default template: origins-reporter-report.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the report information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_origins_reporter_report(array &$variables): void {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

/**
 * Implements hook_user_cancel().
 */
function origins_reporter_user_cancel($edit, UserInterface $account, $method): void {
  switch ($method) {
    case 'user_cancel_block_unpublish':
      // Unpublish reports.
      $storage = \Drupal::entityTypeManager()->getStorage('origins_reporter_report');
      $origins_reporter_report_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->condition('status', 1)
        ->accessCheck(FALSE)
        ->execute();
      foreach ($storage->loadMultiple($origins_reporter_report_ids) as $origins_reporter_report) {
        $origins_reporter_report->set('status', FALSE)->save();
      }
      break;

    case 'user_cancel_reassign':
      // Anonymize reports.
      $storage = \Drupal::entityTypeManager()->getStorage('origins_reporter_report');
      $origins_reporter_report_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->accessCheck(FALSE)
        ->execute();
      foreach ($storage->loadMultiple($origins_reporter_report_ids) as $origins_reporter_report) {
        $origins_reporter_report->setOwnerId(0)->save();
      }
      break;
  }
}

/**
 * Implements hook_ENTITY_TYPE_predelete() for user entities.
 */
function origins_reporter_user_predelete(UserInterface $account): void {
  // Delete reports that belong to this account.
  $storage = \Drupal::entityTypeManager()->getStorage('origins_reporter_report');
  $origins_reporter_report_ids = $storage->getQuery()
    ->condition('uid', $account->id())
    ->accessCheck(FALSE)
    ->execute();
  $storage->delete($storage->loadMultiple($origins_reporter_report_ids));

  // Delete old revisions.
  $origins_reporter_report_ids = $storage->getQuery()
    ->allRevisions()
    ->condition('uid', $account->id())
    ->accessCheck(FALSE)
    ->execute();

  foreach (array_keys($origins_reporter_report_ids) as $revision_id) {
    $storage->deleteRevision($revision_id);
  }
}
