<?php

/**
 * @file
 * Contains origins_social_sharing.module.
 */

use Drupal\Core\Url;

/**
 * Implements hook_theme().
 */
function origins_social_sharing_theme() {
  return [
    'origins_social_sharing' => [
      'variables' => [
        'fb_link' => NULL,
        'x_link' => NULL,
        'mail_link' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_preprocess_block() for block content.
 */
function origins_social_sharing_preprocess_block(&$variables) {
  // Look for the 'social sharing' block.
  if ($variables['plugin_id'] == 'origins_social_sharing') {
    // Get current URL so that we can pass it to Facebook.
    $url = Url::fromRoute('<current>', [], ['absolute' => 'true']);
    $fb_link = 'https://www.facebook.com/sharer/sharer.php?u=' . rawurlencode($url->toString()) . '&amp;src=sdkpreparse';
    $variables['content']['#fb_link'] = $fb_link;
    // Get current node and extract title.
    $node = \Drupal::routeMatch()->getParameter('node');
    $title = '';
    if (!empty($node) && is_object($node)) {
      $title = $node->getTitle();
    }
    // Build X (Twitter) link.
    $x_link = 'https://x.com/intent/post?text=' . rawurlencode($title . ' ') . rawurlencode($url->toString());
    $variables['content']['#x_link'] = $x_link;
    // Build mailto link.
    $mail_link = "mailto:?subject=" . rawurlencode(t("Shared from @host", ['@host' => \Drupal::request()->server->get('HTTP_HOST')]));
    $mail_link .= "&body=" . rawurlencode($title . "\n") . rawurlencode($url->toString());
    $variables['content']['#mail_link'] = $mail_link;
  }
}
