<?php

/**
 * @file
 * Contains origins_shamrock.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function origins_shamrock_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the origins_shamrock module.
    case 'help.page.origins_shamrock':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Operation Shamrock is the NI arrangements for a cabinet office lead directive known as London Bridge. Should this be triggered, this admin page gives a site editor the option as to whether to render the banner on the front page of the site.') . '</p>';
      $output .= '<p>' . t('This module allows accounts with the appropriate permission the ability to toggle the display of the banner if a banner is currently published.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_preprocess_page().
 */
function origins_shamrock_preprocess_page(&$variables) {
  $variables['#cache']['tags'][] = 'origins:operation_shamrock';

  if (\Drupal::config('origins_shamrock.settings')->get('show_banner') && \Drupal::currentUser()->isAnonymous()) {
    $config_factory = \Drupal::configFactory();
    $config = $config_factory->get('origins_shamrock.settings');

    $variables['#attached']['drupalSettings']['origins_shamrock']['service_url'] = $config->get('service_url');
    $variables['#attached']['library'][] = 'origins_shamrock/shamrock_banner';
  }
}
