<?php

/**
 * @file
 * Primary module hooks for Origins Tour module.
 */

/**
 * Implements hook_theme().
 */
function origins_tour_theme() {
  return [
    'help_homepage' => [
      'template' => 'index',
      'variables' => [
        'sitename' => \Drupal::config('system.site')->get('name'),
      ],
    ],
    'tours' => [
      'template' => 'tours',
      'variables' => [
        'tours' => []
      ],
    ],
  ];
}

/**
 * Implements hook_page_attachments().
 */

function origins_tour_page_attachments(array &$attachments) {

    $attachments['#attached']['library'][] = 'origins_tour/tour_modal';

    $attachments['#attached']['drupalSettings']['originsTour'] = [
        'siteName' => 'DEBUG_SITE_NAME',
        'tourName' => 'DEBUG_TOUR_NAME',
    ];

}
