<?php

/**
 * @file
 * Primary module hooks for Origins Cloud Tasks module.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\origins_cloud_tasks\CronTask;
use Drupal\scheduled_transitions\Entity\ScheduledTransitionInterface;

/**
 * Implements hook_entity_insert().
 */
function origins_cloud_tasks_entity_insert(EntityInterface $entity) {
  origins_cloud_tasks_process_scheduled_transition($entity);
}

/**
 * Implements hook_entity_presave().
 */
function origins_cloud_tasks_entity_presave(EntityInterface $entity) {
  origins_cloud_tasks_process_scheduled_transition($entity);
}

/**
 * Process new and existing Cloud Tasks for scheduled transitions.
 */
function origins_cloud_tasks_process_scheduled_transition($entity) {
  if ($entity instanceof ScheduledTransitionInterface) {

    $moderation_state = $entity->get('moderation_state')->getString();

    if ($moderation_state == 'published' || $moderation_state == 'archived') {
      $transition_on = $entity->get('transition_on')->getString();
      $task_id = $entity->bundle() . '--' . $entity->id();

      $task_manager = \Drupal::service('origins_cloud_tasks.manager');

      // If updating a schedule, delete the existing task before recreating it.
      if (!$entity->isNew()) {
        $task_manager->deleteTask($task_id);
      }

      $task = new CronTask($task_id, $transition_on);
      try {
        $task_manager->createTask($task);
      }
      catch (\Exception $ex) {
        \Drupal::messenger()->addError($ex->getMessage());
        \Drupal::logger('origins_cloud_tasks')->error($ex->getMessage());
      }
    }
  }
}
