<?php

/**
 * @file
 * Module install, uninstall and update functions.
 */

use Drupal\field\Entity\FieldStorageConfig;

/**
 * Implementations of hook_update_N().
 */

/**
 * Update hook to switch from field based status to flag.
 */
function origins_toc_update_8001() {
  // Remove toc_enable field if present.
  if ($field_storage = FieldStorageConfig::loadByName('node', 'field_toc_enable')) {
    $field_storage->delete();
  }
}
