<?php

/**
 * @file
 * Contains origins_metatag.module.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function origins_metatag_form_node_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  // Skip over if we have no meta tag field exposed or the user can administer meta tags.
  if (empty($form['field_meta_tags']) || \Drupal::currentUser()->hasPermission('administer meta tags')) {
    return;
  }

  if (\Drupal::currentUser()->hasPermission('view basic meta tags')) {
    // Only show:
    // * Basic: keywords + description elements
    foreach ($form['field_meta_tags']['widget'][0]['basic'] as $key => &$item) {
      if (preg_match('/^#/', $key) || in_array($key, ['title', 'description']) == FALSE) {
        continue;
      }

      $item['#access'] = FALSE;
    }
    // * Advanced: robots element.
    foreach ($form['field_meta_tags']['widget'][0]['advanced'] as $key => &$item) {
      if (preg_match('/^#/', $key) || $key == 'robots') {
        continue;
      }

      $item['#access'] = FALSE;
    }

    // Hide the other options.
    foreach ($form['field_meta_tags']['widget'][0] as $key => &$item) {
      if (preg_match('/^#/', $key) || in_array($key, ['basic', 'advanced'])) {
        continue;
      }

      $item['#access'] = FALSE;
    }
  }
}
