<?php

/**
 * @file
 * Contains origins_metatag.module.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function origins_metatag_form_node_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if (empty($form['field_meta_tags'])) {
    return;
  }
  // Remove any schema_metatag (or submodule) form elements because they make
  // the form so enormously large, it struggles to handle AJAX requests from
  // media entity widgets and cannot generate entity previews.
  // We always want to do this because it'll break the page submission, even
  // for site admins.
  foreach ($form['field_meta_tags']['widget'][0] as $key => $value) {
    if (preg_match('/^schema_/', $key)) {
      $form['field_meta_tags']['widget'][0][$key]['#access'] = FALSE;
    }
  }
  // Skip over if we have no meta tag field exposed or the user can administer
  // meta tags.
  if (empty($form['field_meta_tags']) || \Drupal::currentUser()->hasPermission('administer meta tags')) {
    return;
  }

  // Hide all options by default.
  $form['field_meta_tags']['#access'] = FALSE;

  if (\Drupal::currentUser()->hasPermission('edit basic meta tags')) {
    // Only show:
    // Basic: keywords + description elements.
    foreach ($form['field_meta_tags']['widget'][0]['basic'] as $k => &$item) {
      if (preg_match('/^#/', $k) || in_array($k, ['keywords', 'description'])) {
        continue;
      }

      $item['#access'] = FALSE;
    }

    // Advanced: robots element only.
    if (isset($form['field_meta_tags']['widget'][0]['advanced'])) {
      foreach ($form['field_meta_tags']['widget'][0]['advanced'] as $key => &$item) {
        if (preg_match('/^#/', $key) || $key == 'robots') {
          continue;
            }

            $item['#access'] = FALSE;
        }
    }

    // Hide non-essential groups.
    foreach ($form['field_meta_tags']['widget'][0] as $key => &$item) {
      if (preg_match('/^#/', $key) || in_array($key, ['basic', 'advanced'])) {
        continue;
      }

      $item['#access'] = FALSE;
    }

    $form['field_meta_tags']['#access'] = TRUE;
  }
}
